version: "3.8"

services:
  redis:
    image: redis
    container_name: redis-gateway
    ports:
      - "6379:6979"

  gateway:
    build: .
    container_name: spring-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis